H: 480
RGBD: true
W: 640
anneal_strategy: cos
aux_loss: true
batch_size: 8
beta0: 0.9
beta1: 0.999
class_weights_file: configs/class_weights_scannet20_valid.txt
clean_data: true
data_aug: true
decoder_feat_dim: 256
decoder_head_dim: 256
decoder_in_dim: 128
div_factor: 1.0
epochs: 20
event_dir: logs/ral/MVCNet_full/events
exp_name: MVCNet_full
final_div_factor: 1000.0
fusion_mode: max
ignore_unlabeled: true
learning_rate: 0.0001
log_dir: logs/ral/MVCNet_full
log_root: logs/ral
loss_reduction: mean
loss_reduction_test: mean
lr_decay: 0.2
lr_decay_epochs: 6
num_workers: 8
pct_start: 0.05
preload: false
print_every: 25
projection_dim: [128, 32, 64]
render: false
save_dir: logs/ral/MVCNet_full/checkpoints
save_every: 2
scheduler: onecycle
simple_decoder: false
step: 1
test_file: configs/scannetv2_val.txt
test_orig: true
train_file: configs/scannetv2_train.txt
upsample_mode: bilinear
val_file: configs/scannetv2_val.txt
validate_every: 1
weight_aux: 0.2
weight_decay: 0.0002
weighted_loss_2d: false
window_size: 3